### PR TITLE
Implements `GET` and `POST` on `/api/v1/geofences`

### PR DESCRIPTION
**Pull request by kimar**
@francisdb

https://github.com/Geofancy/cloud-app/issues/8

Also I'd first solve this one to not interrupt production yet. Cloud App still needs tests etc. until then manual testing and lots of caution is necessary to not fuck things up. :see_no_evil:

### CODE REVIEW

**Comment by kimar** [comment]
This still requires the `/developer` documentation to be updated.

**Comment by francisdb** [comment]
Can I somehow see if this is deployed or not?

**Comment by kimar** [comment]
Right now there's no versioning on the cloud app side of things, the only thing you can do is at the server's response headers:

screen shot 2015-12-02 at 11 34 34 am

as you can see this commit is the latest on master and the oAuth routes have also been merged into master. So yes it is. As the commit history gets more complicated this will be harder to find out. I'll be thinking about releasing version of the cloud app just like the iOS app, with a changelog so we can see what's going on more clearly.

**Comment by francisdb** [comment]
Well, a redeploy log is enough for me.

**Comment by kimar** [comment]
I've just added the commit ID to the `/health` endpoint and redeployed the service.

screen shot 2015-12-02 at 8 30 53 pm

Still want to do the changelog thing, but this is a bit easier to look into than going through the response headers.

**Comment by kimar** [comment]
Hopefully not too verbose, but as it's open source I'm sure this will be the last point to find security related bugs :smiling_imp:

**Comment by francisdb** [comment]
Well, https://www.versioneye.com/ and their badge / notifications can help there

**Comment by kimar** [comment]
Will take a look into that, thx

**Pull request merged**
